# version: '3.7'

services:
  # PostgreSQL service for Prisma
  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=postgress
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prisma
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Backend service (Node.js with Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    restart: always
 
    ports:
      - "1337:1337"  # Expose backend port
    depends_on:
       postgres_db:
        condition: service_healthy
    env_file:
      - .env.prod
    networks:
      - app-network
    volumes:
      - ./backend:/app
    working_dir: /app
   
  # Frontend service (React with Vite served by Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Use the production Dockerfile to build the app and serve with Nginx
    restart: always
    ports:
      - "3000:80"  # Expose frontend on port 80 (Nginx default)
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
    working_dir: /app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
